[package]
name = "aesop_trials"
version = "0.1.0"
edition = "2021"
authors = ["Stephen Polentarutti"]
description = "A mythological-themed 2D roguelike dungeon crawler"

[dependencies]
bevy = "0.12"
rand = "0.8"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3